### ISSUE TITLE
Screenshot not capturing correctly!

### ISSUE THREAD

**Issue by StevenW1969** [ravibpatel/CrashReporter.NET#1]
Screenshot only captures a portion of the application on exception error.
![dsasdf](https://cloud.githubusercontent.com/assets/27144976/26786632/49f15d32-49d5-11e7-9aa4-0ae0a2e2d385.png)

**Comment by ravibpatel** [comment]
did you set the CaptureScreen property to true? Like as shown in Readme.

https://github.com/ravibpatel/CrashReporter.NET#capture-whole-screen-instead-of-application-screen

**Comment by StevenW1969** [comment]
Yes I do. I also noticed that it is only on my development workstation. I currently have [4] 28" Samsung 4K monitors at 3480 x 2160 resolution in an extended quadrant configuration so the total overall resolution is 6960 x 4320. I know this is not a standard configuration and is what is most likely the issue. I complied my C# application and installed it on a regular workstation that has [4] 24" Asus HD monitors at 1920 x1200 resolution in an extended quadrant configuration so the total overall resolution is 3840 x 2400. The Screenshot was just fine on this machine. So I came to the conclusion that there must be a limit to the total resolution or that the 4K is an issue.

Our Engineering and development staff all have the HD resolution monitors, the 4K workstation is the new standard that we are changing all our workstations too. 

The majority of our users for this application currently use the HD, but will soon be using 4K.

**Comment by ravibpatel** [comment]
Can you try the utility in below link? It saves a screenshot to the clipboard so you need to paste it into Paint or any other image manipulation program. If it works I can implement it in CrashReporter.NET.

[https://www.dropbox.com/s/4kp50d8xk6rjxok/ScreenCapture_utility.zip?dl=0](url)

**Comment by StevenW1969** [comment]
Ravi, Thanks for getting back with me. I looked at your code a bit and seen that in the public class ReportCrash, line 126 try catch with if else you use the CaptureScreen before the CaptureActiveWindow. Doesn’t this 1st get a Screenshot of the whole screen before attempting to get the Active window? If so may I ask the reasoning for this, I’m curious. Not that it would probably makes much difference.

I downloaded the utility and tried it, but returned the same result.

[sig]
Steve Williams (Product Design Engineer)
1725 Airpark Drive
Grand Haven, MI  49417

O: 616.842.8760 x128
F: 800.842.0644
M: 616.335.4575
http://www.carterbearings.com<http://www.carterbearings.com/>
Engineering Hours are 6:00a-5:00p Mon-Fri EST

**Comment by ravibpatel** [comment]
If you set CaptureScreen to true it will only call the CaptureScreen method of CaptureScreenshot class but if you don't set it then it will be false and it will skip the call to CaptureScreen and only call the CaptureActiveWindow which takes the screenshot and save it to the temp directory.

**Comment by StevenW1969** [comment]
Ravi, Thanks for that, that is the information I was looking for. That helps! I only want a Active Window Shot not the whole screen.

[sig]
Steve Williams (Product Design Engineer)
1725 Airpark Drive
Grand Haven, MI  49417

O: 616.842.8760 x128
F: 800.842.0644
M: 616.335.4575
http://www.carterbearings.com<http://www.carterbearings.com/>
Engineering Hours are 6:00a-5:00p Mon-Fri EST

**Comment by ravibpatel** [comment]
Just don't set the CaptureScreen to anything or set it to false and it will take only active window screenshot.

**Comment by StevenW1969** [comment]
Lol, as I delete the this from my Program.cs file…… “reportCrash.CaptureScreen = false;”

[sig]
Steve Williams (Product Design Engineer)
1725 Airpark Drive
Grand Haven, MI  49417

O: 616.842.8760 x128
F: 800.842.0644
M: 616.335.4575
http://www.carterbearings.com<http://www.carterbearings.com/>
Engineering Hours are 6:00a-5:00p Mon-Fri EST

**Comment by EddieDemon** [comment]
Hi @StevenW1969, it's been quite some time since this issue was opened, but do you still encounter this problem? Or have you created a fix?

**Comment by EddieDemon** [comment]
@ravibpatel I suppose we could close this?

**Comment by ravibpatel** [comment]
@EddieDemon Yeah.
