### ISSUE TITLE
Not Showing Correct Application Version if Network Deployed

### ISSUE THREAD

**Issue by socaljoker** [ravibpatel/CrashReporter.NET#11]
My application is network deployed using the Publish feature in the project properties.

![capto_capture 2018-04-27_10-30-23_am](https://user-images.githubusercontent.com/1231661/39376434-8de55eee-4a06-11e8-8875-2e343bd28327.png)

However, when the crash report screen appears, it show's either the assembly or file version instead of the publish version.

<img width="551" alt="capto_capture 2018-04-27_10-31-48_am" src="https://user-images.githubusercontent.com/1231661/39376423-833eebb8-4a06-11e8-89f0-664ea31d4d3a.png">

I think it should check if it's network deployed, and use the publish version.

`if (ApplicationDeployment.IsNetworkDeployed)
        {
            return ApplicationDeployment.CurrentDeployment.CurrentVersion.ToString();
        }`

**Comment by ravibpatel** [comment]
@socaljoker I will implement in next version. If you like to contribute it you can also open a pull request.
