### ISSUE TITLE
No possible way to send reports silently

### ISSUE THREAD

**Issue by DjordjeMandic** [ravibpatel/CrashReporter.NET#12]
![image](https://user-images.githubusercontent.com/6750655/41425138-22ac9f28-7000-11e8-8e85-9698a91e30c6.png)
There is no option to do it... Im using nuget package 1.5.3
![image](https://user-images.githubusercontent.com/6750655/41425164-361f657c-7000-11e8-96f3-602ebbb8f5b7.png)

**Comment by ravibpatel** [comment]
@DjordjeMandic Please use the library from this [link](https://ci.appveyor.com/api/buildjobs/tn64i3i714wlv2se/artifacts/CrashReporter.NET-1.5.4.zip).

**Comment by DjordjeMandic** [comment]
@ravibpatel Thank you! Im just curious will you update the nuget package?

**Comment by ravibpatel** [comment]
@DjordjeMandic I will. I forgot to update it but now I will do it asap.

**Comment by ravibpatel** [comment]
@DjordjeMandic Updated NuGet package.
