### ISSUE TITLE
Sending silent crash reports dosen't work

### ISSUE THREAD

**Issue by DjordjeMandic** [ravibpatel/CrashReporter.NET#13]
I've just downloaded 1.5.4 nuget pckg and silent tag is not working, tried 5x and still not receiving anything to mail and drdump. Without silent tag it works fine..

**Comment by ravibpatel** [comment]
@DjordjeMandic I tried it and it works fine for me. If your exception is generated on Non-UI thread you should invoke the Send method of the ReportCrash object on UI thread.

```csharp
if (InvokeRequired)
{
	BeginInvoke((MethodInvoker) delegate
	{
		Program.SendCrashReport(exception);
	});
}
```

**Comment by DjordjeMandic** [comment]
@ravibpatel I dont understand it. This is my example code and it works normally without silent tag.

````
[STAThread]
static void Main(string[] args)
{
    initEvents();
    Application.EnableVisualStyles();
    Application.SetCompatibleTextRenderingDefault(false);

    CheckCriticalStartupStuff();
    Startup(args);

    throw new NotImplementedException();
            
    Logger.Okay("Starting main window.");
    using (var mainWindow = new MainWindow())
    {
        Application.Run(mainWindow);
    }

    Dispose();
}
````

In initEvents i've subscribed to thread and unhandled exceptions, everything works normally like that but Silent tag wont work.

But if i set silent to true then it just executed whole Send method without doing anything.

**Comment by ravibpatel** [comment]
@DjordjeMandic Can you please try the new build from [here](https://ci.appveyor.com/api/buildjobs/x5ik0ns39eq74xc9/artifacts/CrashReporter.NET-1.5.4.zip) to see if it fixes your problem?

**Comment by ravibpatel** [comment]
@DjordjeMandic Update nuget package to v1.5.5.
