### ISSUE TITLE
How does it handles an OutOfMemoryException?

### ISSUE THREAD

**Issue by rafael-biz** [ravibpatel/CrashReporter.NET#20]
If an application gets out of memory because of a memory leek, how does CrashReporter.NET manages to handle it and send the reports?

And what if an application reaches the maximum number of sockets supported, how does it sends the reports?

**Comment by rafael-biz** [comment]
Hi @PandaWood,

Thanks for the clarification. So, if I got it right, the CrashReporter.NET relyies on catching unhlanded exceptions by adding an event handler on **AppDomain.CurrentDomain.UnhandledException**, right?

**Comment by ravibpatel** [comment]
@rafael-biz Yes, That is correct.
