### ISSUE TITLE
use custom smtp host not work

### ISSUE THREAD

**Issue by ahmadstout** [ravibpatel/CrashReporter.NET#23]
``````
var reportCrash = new ReportCrash("ahmad.sattot@gmail.com")
            {
                AnalyzeWithDoctorDump = false,
                SmtpHost = "send.one.com",
                Port = 465,
                EnableSSL = true,
                UserName = "crash_report@developer-solution.com",
                Password = "******",
                ToEmail = "ahmad.sattot@gmail.com",
                FromEmail = "crash_report@developer-solution.com",
                DeveloperMessage = developerMessage,
                //Silent = silent,
                CaptureScreen = true
            };
```````````

progress bar still spinning and please wait...

**Comment by PeterEJensen** [comment]
Yep, same error here. Any fix for this?

**Comment by ravibpatel** [comment]
Do you get any errors?

**Comment by PeterEJensen** [comment]
![error](https://user-images.githubusercontent.com/15614913/58264493-41838380-7d7e-11e9-8857-f83a3ffa024d.PNG)


```
            var reportCrash = new ReportCrash("")
            {

                AnalyzeWithDoctorDump = false,
                SmtpHost = "smtp.office365.com",
                Port = 587,
                EnableSSL = true,
                UserName = "",
                Password = "",
                ToEmail = "",
                FromEmail = "",
               // CaptureScreen = true,
               
                DeveloperMessage = developerMessage
          
```
I've attached the error and how my code looks. I've removed the mail and password, but you get the idea of how I set it up.

From the error, it seems like an SMTP error, but the office smtp works fine from other places

**Comment by PeterEJensen** [comment]
Any update on this or am I doing something wrong?

**Comment by ravibpatel** [comment]
It is not possible to reproduce the issue without real SMTP credentials. You can try to addiing the project to your solution and debug it. That way you can tinker with SMTP settings from inside. You may find the code responsible for sending mail [here](https://github.com/ravibpatel/CrashReporter.NET/blob/master/CrashReporter.NET/ReportCrash.cs#L237-L245).

**Comment by EddieDemon** [comment]
@ahmadstout Can you please try port 587 without SSL.

@PeterEJensen Can you please disable SSL and - if you use multi-factor authentication - make sure that you use an app password instead of the modern authentication password.

**Comment by EddieDemon** [comment]
@ravibpatel - Issue should be closed.
