### ISSUE TITLE
Sending all crashes?

### ISSUE THREAD

**Issue by ktownmods** [ravibpatel/CrashReporter.NET#24]
Hey, does this crash reporter send any crashes of a program?
I mean, if I have a problem in my code
e.g. a con string for mysql and I write instead of server serverr, then that gives a crash
will this be sent automatically?
because i think it dont do that, or i make anything wrong
Sorry for my bad english

**Comment by ravibpatel** [comment]
Yes, It will send all crashes automatically unless you specifically handled the exception and suppressed it.

**Comment by ktownmods** [comment]
Thanks
