### ISSUE TITLE
[Q] Is drdump guid needed?

### ISSUE THREAD

**Issue by DjordjeMandic** [ravibpatel/CrashReporter.NET#25]
I think that i didnt specify any guid for drdump and im still receiving crash reports over there, basically only specified email. How come?

**Comment by ravibpatel** [comment]
@DjordjeMandic If you don't specify GUID then it will still use DrDump to send you an email. If you don't want to send reports using DrDump then you can to set up your SMTP details and set AnalyzeWithDoctorDump to false.

**Comment by DjordjeMandic** [comment]
@ravibpatel Im receiving mails from drdump but crash list on drdump on their website also receives full dumps without guid specified. Does drdump handle mail as guid? I set ToEmail to same email address that i use to login in drdump acc. 
![image](https://user-images.githubusercontent.com/6750655/61591900-4cb32e00-abcc-11e9-9586-1c617a5c22aa.png) see? 
![image](https://user-images.githubusercontent.com/6750655/61591923-6c4a5680-abcc-11e9-85a3-f7b71a9e9e9d.png) No guid specified anywhere in program.

**Comment by ravibpatel** [comment]
I haven't designed the DrDump related functionality. It was added by the author of DrDump as a pull request. So I am not sure if it can use Email as GUID or not. If you want to disable DrDump related functionality then you can set AnalyzeWithDoctorDump to false.

**Comment by EddieDemon** [comment]
@ravibpatel - Issue should be closed.
