### ISSUE TITLE
Doesn't handle no internet connection

### ISSUE THREAD

**Issue by bewster** [ravibpatel/CrashReporter.NET#27]
We have a Windows device that can start up without any Internet connection.
If an application crashes the dialog is not shown; but application silently closes.

From what I can determine, `SendRequestState.GetMacAddress` throws an uncaught `SocketException` due to an unreachable network.

**Comment by ravibpatel** [comment]
Do have the stack trace? I can determine the point of failure and make send button hidden when that's the case so users can see the dialog and they can save the report to send it via email later on.

**Comment by bewster** [comment]
I was provided with these:

![crash-1](https://user-images.githubusercontent.com/3236592/65674436-73feff00-e044-11e9-9c31-745d77a4221b.PNG)

![crash-2](https://user-images.githubusercontent.com/3236592/65674441-77928600-e044-11e9-896d-95f12ac989ab.PNG)

They are from 1.5.0 build.  Since updating to 1.5.8 I have not seen the UI displayed at all, the application is just terminated, with a WER report created.

**Comment by ravibpatel** [comment]
I fixed the issue in the latest commit. Can you please try it from [here](https://ci.appveyor.com/api/buildjobs/afhnr17vn3u8ehsq/artifacts/CrashReporter.NET-1.5.9.zip) and let me know if it works properly?
