### ISSUE TITLE
[Q] use ClickOnce deployment version instead of the AssemblyInfo 

### ISSUE THREAD

**Issue by mystical2005** [ravibpatel/CrashReporter.NET#32]
I would like to have a ability to use the ClickOnce deployment version, as that is automatically updated and that what the end user will see.
Thank you for a great application.

**Comment by ravibpatel** [comment]
It does use ApplicationDeployment.CurrentDeployment.CurrentVersion when ApplicationDeployment.IsNetworkDeployed is true as you can see [here](https://github.com/ravibpatel/CrashReporter.NET/blob/master/CrashReporter.NET/ReportCrash.cs#L156-L158).

**Comment by mystical2005** [comment]
you are absolutely right. 
i was running it locally and not getting that info. 
Thank you again for this code. Made my life easier :)

**Comment by ravibpatel** [comment]
You are welcome.
