### ISSUE TITLE
How to set this Email parameter properly?

### ISSUE THREAD

**Issue by Wonderdch** [ravibpatel/CrashReporter.NET#36]
![snipaste20201228_130641](https://user-images.githubusercontent.com/12708888/103190826-95b4f900-490d-11eb-9ff2-b9c760dfd537.png)

Just like picture shows, this Email is emtpy when crash form showed. And it only work whether keep empty or filled in FromEmial(eg 476681123@qq.com).  

When my user see this form, they always tends to fill in their own email,and failed:
![snipaste20201228_132016](https://user-images.githubusercontent.com/12708888/103191306-74eda300-490f-11eb-8cd2-eb4042faaa88.png)

How can i make this Email textbox invisible or filled with correct mail address by config?

Here is my ReportCrash setting:
```cs
_reportCrash = new ReportCrash("dongzige@csmc.com")
{
    Silent = true,
    IncludeScreenshot = true,
    AnalyzeWithDoctorDump = false,
    SmtpHost = "smtp.qq.com",
    Port = 587,
    EnableSSL = true,
    UserName = "476681123@qq.com",
    Password = "XXX",
    ToEmail = "dongzige@csmc.com",
    FromEmail = "476681123@qq.com",
};
```

**Comment by ravibpatel** [comment]
Can you try the new build from [here](https://ci.appveyor.com/api/buildjobs/h0xkd13q4itj8cjj/artifacts/CrashReporter.NET-1.6.0.zip)? It should fix the issue.

**Comment by Wonderdch** [comment]
> Can you try the new build from [here](https://ci.appveyor.com/api/buildjobs/h0xkd13q4itj8cjj/artifacts/CrashReporter.NET-1.6.0.zip)? It should fix the issue.

I tried, But it's getting worse 😅

No matter what i input in Email Textbox or keep it empty, i always got the expection "Failed to send email":

![snipaste20201229_100749](https://user-images.githubusercontent.com/12708888/103253900-074c8000-49be-11eb-840e-a39a19575caa.png)

And Email Textbox still is emtpy when crash form showed.
![snipaste20201229_100640](https://user-images.githubusercontent.com/12708888/103254013-9fe30000-49be-11eb-88a2-8f86398696e6.png)

**Comment by ravibpatel** [comment]
Can you try this build from [here](https://ci.appveyor.com/api/buildjobs/cak893p0w2p8c73x/artifacts/CrashReporter.NET-1.6.0.zip)? It should fix the issue.

**Comment by Wonderdch** [comment]
> Can you try this build from [here](https://ci.appveyor.com/api/buildjobs/cak893p0w2p8c73x/artifacts/CrashReporter.NET-1.6.0.zip)? It should fix the issue.

Amazing! It worked.

![snipaste20201229_151818](https://user-images.githubusercontent.com/12708888/103265696-26143c00-49e9-11eb-9237-5415e8cd53e3.png)
