### ISSUE TITLE
Not getting Mail if i set AnalyzeWithDoctorDump= "false".

### ISSUE THREAD

**Issue by koushik077** [ravibpatel/CrashReporter.NET#4]
If i set AnalyzeWithDoctorDump as false i am not getting mail. @ravibpatel

**Comment by ravibpatel** [comment]
Try it like this.

```csharp
var reportCrash = new ReportCrash
{
	AnalyzeWithDoctorDump = false,
	SmtpHost = "smtp.gmail.com",
	Port = 465
	EnableSSL = true,
	UserName = "Your Gmail Account Email",
	Password = "Your Gmail Account Password",
        ToEmail = "Email address where you want receive crash reports",
	FromEmail = "Any Email you want",
	DeveloperMessage = developerMessage,
};
```

**Comment by koushik077** [comment]
I tried that but i am getting following error:
![creporter_error](https://user-images.githubusercontent.com/25477013/29455161-bc1ada4a-842d-11e7-96cc-bb9234460757.PNG)

**Comment by ravibpatel** [comment]
Can you try following steps.

[Allowing less secure apps to access your account](https://support.google.com/accounts/answer/6010255?hl=en)

**Comment by koushik077** [comment]
I got the same error after allowing less secure apps to access my gmail account

**Comment by ravibpatel** [comment]
Try 587 in Port.

**Comment by koushik077** [comment]
Yeah it worked. Thanks
