### ISSUE TITLE
WPF-Example

### ISSUE THREAD

**Issue by Danielmdmu** [ravibpatel/CrashReporter.NET#5]
Is there any Example how I can intergrate CrashReporter.NET in my WPF-Application?

**Comment by ravibpatel** [comment]
I updated the documentation. You can find it [here](https://github.com/ravibpatel/CrashReporter.NET#wpf-application).

**Comment by Danielmdmu** [comment]
Thanky you

**Comment by ravibpatel** [comment]
You may need to rebuild the library from project source. I fixed a problem with WPF application where crash report form doesn't look good because Visual Styles are not enabled in WPF application.
