### ISSUE TITLE
Changing any form property corrupts resource file

### ISSUE THREAD

**Issue by DjordjeMandic** [ravibpatel/CrashReporter.NET#7]
Without any changes to form it compiles nicely, but if i change icon of form resource file gets corrupted https://stackoverflow.com/questions/45928710/resource-file-getting-corrupted-if-something-is-changed

**Comment by ravibpatel** [comment]
My bad. I added strings to Form's RESX files and Visual Studio regenerate Form's RESX file when you change something. So the manually added resource files get lost when VS do this. I will move them to Project's RESX file as soon as possible.
