### ISSUE TITLE
Email error report without creating reporting popup?

### ISSUE THREAD

**Issue by NateVolt** [ravibpatel/CrashReporter.NET#8]
I have implemented this into a WFA. However, I would like for the reporting to be done automatically. Instead, the submit error form pops up and asks for email despite providing it in the initialization of the crash reporter. Is there a way to hide the error form and just send without asking the user for input?

**Comment by ravibpatel** [comment]
@NateVolt There is functionality to submit reports automatically but it will always show the dialog. It will send useful information regarding bug silently by default.
